# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

jobs:
- job: CreateWindows10VMWithTerraform
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: HashiCorpTerraformInstaller@0
  displayName: 'Install Terraform'
    inputs:
      terraformVersion: latest
      
  - script: |
      python -m pip install --upgrade pip
      pip install requests
    displayName: 'Install Python requests library'

  - script: |
      az login --service-principal -u 0cd2a780-3598-4328-8db8-8b7ba273e024 -p 7wj8Q~ZoQE19B3yHSRlA9XoXzu63nIHjCWuI8a1Z --tenant c86959ed-45e5-47f5-8ef5-308ca79916fc
      cd $(Agent.BuildDirectory)
      git clone https://github.com/hashicorp/learn-terraform-azure.git
      cd learn-terraform-azure

      terraform init
      terraform plan -out=tfplan -var="prefix=mywindowsvm" -var="location=eastus"
      terraform apply -auto-approve tfplan
    displayName: 'Create Windows 10 VM with Terraform'



